# Generated by Django 5.1 on 2024-09-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_users_password_alter_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
