# Generated by Django 5.1 on 2024-09-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='rate',
        ),
    ]
