# Generated by Django 5.1 on 2024-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_price_service_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
