# Generated by Django 5.1 on 2024-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
