# Generated by Django 5.1 on 2024-10-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_servicecategory_servicesubcategory_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='servicesubcategory_images/'),
        ),
    ]
