# Generated by Django 5.1 on 2024-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_servicesubcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
