# Generated by Django 5.1 on 2024-10-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_interview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
