# Generated by Django 5.1 on 2024-10-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='employee_certificates/'),
        ),
    ]
