# Generated by Django 5.1 on 2024-10-18 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_employee_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
