# Generated by Django 5.1 on 2024-10-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_client_status_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='qualification',
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
