# Generated by Django 5.1 on 2024-10-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_employee_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specialization',
        ),
        migrations.AddField(
            model_name='employee',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='myapp.specialization'),
        ),
    ]
