# Generated by Django 5.1 on 2024-10-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_employee_is_on_leave_employee_leave_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
