# Generated by Django 5.1 on 2024-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_remove_employee_is_on_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
