# Generated by Django 5.1 on 2024-10-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_employee_contact_alter_employee_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_on_leave',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_end',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='leave_start',
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(),
        ),
    ]
