# Generated by Django 5.1 on 2025-01-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_client_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategoryMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_categories_men', to='myapp.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubcategoryMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='servicesubcategory_images_men/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories_men', to='myapp.servicecategorymen')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rate', models.DecimalField(decimal_places=2, help_text='Rate in Indian Rupees', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images_men/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_men', to='myapp.servicesubcategorymen')),
            ],
        ),
    ]
