# Generated by Django 5.1 on 2025-01-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_servicecategorymen_servicesubcategorymen_servicemen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('before_image', models.ImageField(upload_to='hairstyles/before/')),
                ('after_image', models.ImageField(upload_to='hairstyles/after/')),
            ],
        ),
    ]
