# Generated by Django 5.1 on 2025-01-23 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_payment_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='payment',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='myapp.offer'),
        ),
    ]
