# Generated by Django 5.1 on 2025-03-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_payment_razorpay_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hair_problem_images/')),
                ('hair_type', models.CharField(max_length=50)),
            ],
        ),
    ]
