# Generated by Django 5.1 on 2025-03-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_hairtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HairType',
        ),
    ]
